In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [4]:
array= np.linspace(-3,3,num=100)
array+100

array([ 97.        ,  97.06060606,  97.12121212,  97.18181818,
        97.24242424,  97.3030303 ,  97.36363636,  97.42424242,
        97.48484848,  97.54545455,  97.60606061,  97.66666667,
        97.72727273,  97.78787879,  97.84848485,  97.90909091,
        97.96969697,  98.03030303,  98.09090909,  98.15151515,
        98.21212121,  98.27272727,  98.33333333,  98.39393939,
        98.45454545,  98.51515152,  98.57575758,  98.63636364,
        98.6969697 ,  98.75757576,  98.81818182,  98.87878788,
        98.93939394,  99.        ,  99.06060606,  99.12121212,
        99.18181818,  99.24242424,  99.3030303 ,  99.36363636,
        99.42424242,  99.48484848,  99.54545455,  99.60606061,
        99.66666667,  99.72727273,  99.78787879,  99.84848485,
        99.90909091,  99.96969697, 100.03030303, 100.09090909,
       100.15151515, 100.21212121, 100.27272727, 100.33333333,
       100.39393939, 100.45454545, 100.51515152, 100.57575758,
       100.63636364, 100.6969697 , 100.75757576, 100.81818182,
       100.87878788, 100.93939394, 101.        , 101.06060606,
       101.12121212, 101.18181818, 101.24242424, 101.3030303 ,
       101.36363636, 101.42424242, 101.48484848, 101.54545455,
       101.60606061, 101.66666667, 101.72727273, 101.78787879,
       101.84848485, 101.90909091, 101.96969697, 102.03030303,
       102.09090909, 102.15151515, 102.21212121, 102.27272727,
       102.33333333, 102.39393939, 102.45454545, 102.51515152,
       102.57575758, 102.63636364, 102.6969697 , 102.75757576,
       102.81818182, 102.87878788, 102.93939394, 103.        ])

In [5]:
np.random.randint(50,high=101,size=100)

array([54, 61, 79, 91, 81, 88, 73, 87, 92, 68])

In [10]:
np.random.randint(50,size=(50,5),high=100)

array([[58, 65, 57, 84, 53],
       [64, 77, 51, 55, 84],
       [79, 63, 66, 73, 99],
       [85, 94, 58, 81, 63],
       [79, 82, 92, 69, 95],
       [52, 70, 73, 51, 83],
       [76, 78, 67, 71, 51],
       [99, 53, 92, 63, 71],
       [67, 71, 77, 57, 74],
       [89, 52, 54, 67, 94],
       [60, 95, 89, 60, 58],
       [91, 66, 99, 59, 99],
       [63, 57, 67, 96, 62],
       [63, 76, 66, 94, 83],
       [70, 75, 54, 59, 60],
       [87, 53, 50, 81, 55],
       [91, 86, 82, 63, 88],
       [99, 55, 85, 95, 53],
       [52, 57, 97, 87, 63],
       [67, 56, 56, 80, 71],
       [66, 53, 56, 87, 98],
       [98, 64, 99, 72, 76],
       [85, 86, 76, 82, 95],
       [60, 65, 79, 73, 53],
       [78, 65, 70, 54, 86],
       [73, 97, 64, 92, 55],
       [70, 99, 72, 93, 64],
       [78, 67, 96, 70, 80],
       [77, 91, 92, 58, 60],
       [98, 60, 61, 59, 58],
       [95, 83, 70, 96, 70],
       [57, 68, 54, 79, 95],
       [73, 71, 76, 79, 75],
       [93, 96, 58, 71, 64],
       [99, 58, 68, 98, 65],
       [65, 58, 63, 91, 93],
       [98, 89, 98, 51, 91],
       [53, 85, 57, 60, 98],
       [78, 55, 78, 91, 84],
       [86, 99, 59, 88, 76],
       [87, 95, 93, 51, 77],
       [67, 76, 87, 92, 64],
       [91, 96, 70, 79, 58],
       [74, 79, 55, 77, 95],
       [50, 61, 93, 82, 52],
       [52, 52, 83, 85, 73],
       [86, 54, 67, 97, 55],
       [76, 67, 84, 85, 78],
       [90, 68, 54, 57, 84],
       [67, 64, 78, 65, 84]])

In [15]:
content=np.random.randint(50,size=(50,5),high=101)
import pandas as pd
df1=pd.DataFrame(data=content,
             index=range(1,51),
             columns=['國','英','數','社','自'])
df1

      國   英    數   社    自
1    79  99   91  61   56
2    54  60   87  85   75
3    68  90   76  56   82
4    79  69   82  62   96
5    77  79   75  88   82
6    86  51   86  53   69
7   100  57   98  96   94
8    59  95   63  76   58
9    54  90   64  89   90
10   75  88   75  69   89
11   92  71   56  57   70
12   51  75   74  77   92
13   98  55   99  74   79
14   98  95   71  50   56
15   51  85   71  71   50
16   53  87   77  66   94
17   68  50   87  92   54
18   50  59   84  59   71
19   61  75   90  72   57
20   57  84   68  50   58
21   50  63   78  56   81
22   64  50   80  52   78
23   82  67   72  64   89
24   74  74   88  80   51
25   65  89   84  64   80
26   91  68   83  60   57
27   71  57   96  68   60
28   62  77   50  82   79
29   98  91   88  73   77
30   89  51   92  71   99
31   83  62   65  97   51
32   73  74   63  60   94
33   53  69   80  52   70
34   70  93   84  58   65
35   95  92   81  51   94
36   79  52   85  58   75
37   69  88   72  88   68
38   70  77   95  74   85
39   50  72   72  67   63
40   71  55  100  97   66
41   82  64   61  80   89
42   76  56   77  88   61
43   97  73   98  80   79
44   81  94   97  88   80
45   89  65   55  94   69
46   81  82   63  89   88
47   81  97   70  95   89
48   94  88   91  51   79
49   87  69   97  58  100
50   58  59   75  64   71

In [16]:
df1['國']+df1['數']

1     170
2     141
3     144
4     161
5     152
6     172
7     198
8     122
9     118
10    150
11    148
12    125
13    197
14    169
15    122
16    130
17    155
18    134
19    151
20    125
21    128
22    144
23    154
24    162
25    149
26    174
27    167
28    112
29    186
30    181
31    148
32    136
33    133
34    154
35    176
36    164
37    141
38    165
39    122
40    171
41    143
42    153
43    195
44    178
45    144
46    144
47    151
48    185
49    184
50    133
dtype: int64